### ISSUE TITLE
error 9.1

### ISSUE THREAD

**Issue by gaveer** [alarofrunetotem/OrderHallCommander#14]
```
16x OrderHallCommander\cache.lua:901: attempt to compare number with nil
[string "@OrderHallCommander\cache.lua"]:901: in function `GetFullPermutations'
[string "@OrderHallCommander\matchmaker.lua"]:691: in function `?'
[string "@OrderHallCommander\missionlist.lua"]:544: in function <OrderHallCommander\missionlist.lua:528>
[string "=(tail call)"]: ?
[string "@OrderHallCommander\missionlist.lua"]:365: in function `?'
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:90: in function `UpdateMissions'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua"]:844: in function <...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:843>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2734: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2641: in function <FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3492: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:1976: in function <FrameXML\UIParent.lua:1287>

Locals:
self = <table> {
 MAXLEVEL = <function> defined @OrderHallCommander\OrderHallCommander.lua:137
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 IsBlacklisted = <function> defined @OrderHallCommander\core.lua:165
 GetAverageLevels = <function> defined @OrderHallCommander\cache.lua:944
 allEquipments = <table> {
 }
 RebuildMissionCache = <function> defined @OrderHallCommander\cache.lua:931
 GetDataModule = <function> defined @OrderHallCommander\data.lua:14
 ActivateButton = <function> defined @OrderHallCommander\core.lua:199
 GetDifficultyColors = <function> defined @OrderHallCommander\core.lua:226
 GetMissionlistModule = <function> defined @OrderHallCommander\missionlist.lua:16
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 MAXQUALITY = <function> defined @OrderHallCommander\OrderHallCommander.lua:140
 GetResources = <function> defined @OrderHallCommander\cache.lua:744
 GetCacheModule = <function> defined @OrderHallCommander\cache.lua:16
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 GetCompletedMissionData = <function> defined @OrderHallCommander\autocomplete.lua:570
 MarkAsSeen = <function> defined @OrderHallCommander\core.lua:289
 ReloadMissions = <function> defined @OrderHallCommander\missionlist.lua:566
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Pulse = <function> defined @OrderHallCommander\missionlist.lua:642
 hooks = <table> {
 }
 db = <table> {
 }
 PauseApply = <function> defined @OrderHallCommander\missionlist.lua:495
 Apply = <function> defined @OrderHallCommander\missionlist.lua:498
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 EmptyPermutations = <function> defined @OrderHallCommander\cache.lua:849
 PushRefresher = <function> defined @OrderHallCommander\missionlist.lua:557
 Reserve = <function> defined @OrderHallCommander\OrderHallCommander.lua:213
 Reward2Class = <function> defined @OrderHallCommander\cache.lua:432
 ColorFromBias = <function> defined @OrderHallCommander\OrderHallCommander.lua:149
 NeedsTutorial = <function> defined @OrderHallCommander\tutorials.lua:413
 ShowPermutations = <function> defined @OrderHallCommander\missionpage.lua:290
 OnInitialized = <function> defined @OrderHallCommander\core.lua:142
 GetMissionpageModule = <function> defined @OrderHallCommander\missionpage.lua:16
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 GetMembersFrame = <function> defined @OrderHallCommander\missionlist.lua:808
 SortTroop = <function> defined @OrderHallCommander\cache.lua:814
 CleanPermutations = <function> defined @OrderHallCommander\missionlist.lua:393
 revision = "cc8ae7d"
 Unban = <function> defined @OrderHallCommander\OrderHallCommander.lua:228
 GetSelectedParty = <function> defined @OrderHallCommander\matchmaker.lua:653
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 DumpPermutations = <function> defined @OrderHallCommander\cache.lua:923
 name = "OrderHallCommander"
 RefillParties = <function> defined @OrderHallCommander\matchmaker.lua:687
 TroopsWillDieAnyway = <function> defined @AddO
 ```

**Comment by gaveer** [comment]
@alarofrunetotem

**Comment by alar77** [comment]
What were you doing? Freshly tested with a demon hunter using start quick first mission with no issues

**Comment by gaveer** [comment]
i open mission table and send mission and boom error lua

**Comment by Kelsuwa** [comment]
Just wanted to add to this - the addon was working fine for me on Thursday (July 8th) but today I got an error that appears to be the same as the one above.  It occurred on opening the mission table and then it re-occurs on any interaction with the table (e.g. hover mouse over a mission, scroll the mission log).  Reloading the UI/restarting the WoW client doesn't appear to make any difference.

What I did notice is that I'm getting the error on my main (DK), but when I switched to my DH the error is not triggering.  This suggests to me the issues is caused by something stateful/contextual ... but not sure how to prove that.  Hope this helps ...

Addon version:  1.9.0

Message: Interface\AddOns\OrderHallCommander\cache.lua:901: attempt to compare number with nil
Time: Sat Jul 10 10:36:05 2021
Count: 2
Stack: Interface\AddOns\OrderHallCommander\cache.lua:901: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface\AddOns\OrderHallCommander\cache.lua"]:901: in function `GetFullPermutations'
[string "@Interface\AddOns\OrderHallCommander\matchmaker.lua"]:691: in function `?'
[string "@Interface\AddOns\OrderHallCommander\missionlist.lua"]:544: in function <Interface\AddOns\OrderHallCommander\missionlist.lua:528>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\OrderHallCommander\missionlist.lua"]:365: in function `?'
[string "@Interface\AddOns\BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua"]:90: in function `UpdateMissions'
[string "@Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua"]:844: in function <...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:843>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2734: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2641: in function <Interface\FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3492: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1976: in function <Interface\FrameXML\UIParent.lua:1287>

Locals:

**Comment by Kelsuwa** [comment]
Not sure if this is related to the issue at all, but after disabling the addon I noticed another issue when using the Legion table through what I think is the vanilla Blizzard UI (i.e. I don't think I have any other addons that modify it enabled).  I noticed in my Followers list I have a set of Krokul Ridgestalkers that appear to be miss-sorted (they're at the bottom of the list rather than grouped together like all the other follower variants) and when I click on them I get an error (see below).  I'm just wondering if this issue is the root cause of the issue being seen in the addon assuming it's trying to calculate the best selections for missions and failing to select the bugged unit?

Message: ...rrisonTemplates\Blizzard_GarrisonSharedTemplates.lua:2274: attempt to index local 'color' (a nil value)
Time: Sat Jul 10 11:31:25 2021
Count: 6
Stack: ...rrisonTemplates\Blizzard_GarrisonSharedTemplates.lua:2274: attempt to index local 'color' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonSharedTemplates.lua"]:2274: in function `ShowFollower'
[string "@Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonSharedTemplates.lua"]:1380: in function `ShowFollower'
[string "@Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonSharedTemplates.lua"]:1012: in function `GarrisonFollowerListButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:

**Comment by alar77** [comment]
Interesting hint, I am wondering how can I make this happen..
Anyway I released a BandAid patch.Not really foxes the issue but at leasrt avoid crasching the whole thing

**Comment by Kelsuwa** [comment]
I made a point of sending the "bugged" Krokul Ridgestalkers on two missions yesterday so that they were exhausted.  I then recruited some more and found that they also appeared to be "bugged", so it may be creating new units is a way to test this theory.  I still have the other Krokul Ridgestalkers that I recruited prior to 9.1 and they seem to be fine.  I'm afraid that's about as "scientific" as I can get ... sorry.  :)
